import { spawn } from "node:child_process";
import { createServer } from "node:net";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { OpenCodeHttp } from "../src/integrations/opencode-http.ts";
const freePort = () => new Promise<number>((res, rej) => { const s = createServer(); s.once("error", rej); s.listen(0, "127.0.0.1", () => { const p = (s.address() as { port: number }).port; s.close(() => res(p)); }); });
const cwd = mkdtempSync(join(tmpdir(), "diag-exit-"));
const username = process.env.OPENCODE_SERVER_USERNAME ?? "";
const password = process.env.OPENCODE_SERVER_PASSWORD ?? "";
const port = await freePort();
const env = { ...process.env }; delete env.OPENCODE_PID; delete env.OPENCODE;
const child = spawn("/usr/local/bin/opencode", ["serve","--hostname","127.0.0.1","--port",String(port)], { cwd, env, stdio:["ignore","ignore","ignore"] });
const http = new OpenCodeHttp({ baseUrl:`http://127.0.0.1:${port}`, password, username, timeoutMs:8000 });
const auth = password ? { Authorization:`Basic ${Buffer.from(`${username}:${password}`).toString("base64")}` } : {};
for (let i=0;i<80;i++){ try { const r=await fetch(`http://127.0.0.1:${port}/doc`,{headers:auth,signal:AbortSignal.timeout(2000)}); if(r.ok) break; } catch{} await new Promise(r=>setTimeout(r,250)); }
const created = await http.createSession(cwd);
await http.listSessions(cwd);
await http.getSession(created.id);
await http.sessionStatus();
await http.listMessages(created.id);
await http.firstEvent(8000);
await http.abortSession(created.id);
await http.deleteSession(created.id);
console.log("ALL DONE (natural exit next)");
child.kill("SIGTERM");
await new Promise((r)=>child.once("exit",r));
console.log("child exited; draining");
